language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master


deploy:
  provider: heroku
  app: todo-app-fe-studying
  api_key:
    secure: "dfaf4da5-4823-47a7-949e-b90b49c1ecd0"