language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: todo-app-fe-studying
  api_key:
    secure: nuRCo1lo9YXwZ37wn1YIATV5B67ZSJ0Ns3CVVeAik1c+oNfnut3ooGlebrVCS7SlTsbt6tL4hdseR+QskYxxLZ4ZxH0ABoqBWxeqjVNq2Ev3FUxAhS97api7UFIfcOuOST7ZqmvsKTbZu7VdPbqHYuBZECnpAIXkIiuQ/0uAqDm6yQj7FDTlJ6UScK5a5oRItAqfZAG3bW/MzNQpgBtf2+5huXQRd50ZsaQZfyfugtTjmC68iF1iKItbhyvkBZkVOucHCgBJ5vXgk9VBPt1GNaX6dOBk9XmwotfVLVaMMsK1jq8ajVJtq51r3xuuf35faTxn3VAjAuDwLHFfli53fMJc4IUOU0+7p8keOqog6NgknprlvOqciCMubCmqqkSNoTUZ6sxPtcKLbiHC4Txf9fu7fZthz9w8m5ApaAVpc+6h5Kb+An3lsfx1DNrHkYYGyyOigKEuqLrh+VorJ+c2PSmi1gP5PgBX2BEwoGy+qNj0T7yro4oAFOOyc0/64jOcEb/sZWig4rMy0mB0VeD3rSHAk370YMMLVoUr0kRD5Px9O5oYTxYL+A+eb+2zupKjigZO468NiUv0dQhm9sRaQzn3AmGtV2lH+MxUtN6FEN1OjPPlm78g+/t2EfuqVY4Vz8/tG5xOseJcHBZa5+XeGRwnADHpVusDHOqzbAS5+N4=
