language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master


deploy:
  provider: heroku
  app: todo-app-fe-studying
  api_key:
    secure: "c91016b3-78dd-4bea-9336-8cb76ad3cc47"