language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
- npm link @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: todo-app-fe-studying
  skip_cleanup: true
  api_key:
    secure: nHV1uz7MxSHo7pKFyOQHu2TZtb/QMUa0zUqbqDQ90Z6yaIODPJ7T6kAHJcPR0vSmVY1DyCpnCnSTw0vYspBERt6VWGW6FI9G3X6L3uG7R3X630E0Rh1qSmlgP5XQPZcFKxEH9VbcgLAQKv3O6Ydmb2SK/FQYP35+dd0cMOVhn0019bxl3huuCudJMS/5oOSM39oN1EF3+TwsLbu9YG/81UzDBH5yXZcX+tje8jOuMEZ5KDURfofecS+/N2QbIDw86OD+7bGZtEjHNBZktLB+D8Lxsz+UEnpbIM5/eeoOZOVxqoAeMO/6iY6t0+VZJYGsFBxmg53Tq/RzQA99NW8DZc46W9uqgOxizntKA+0TgNmzZBK1jKpsi5rz4ttXFBeEX3zmZJHGJGeKcdj6SGtWTA+nBBysXZyYjRsu5DqofxC7wulhjbAX/hX1eX37QPDVsg+CpIWAVtc2YYAcosJhuQLZcD5L/1y71k1pM0aolG2axtizLx5bpifcWaXuboh8sHOqKGw/hY1yT+vy7Izd+c5FFvc2DuOesbji0Q/eJoNvKFPW0DB4mSKsw/v9+sau/OHEI0daNImiOu76sbGrD/ovDwvtZ+sJe+ngP+pGbLw7QJVgZ6CyhxiIVDTB4iseYZoUHYKQDSKOWtfHPoAqbunEhz5UBZPOJ8/tt3YrwcE=
